### PR TITLE
HTML Forms project

### PR DESCRIPTION
**Pull request by Abhigyan001**
**Intuit Signup page clone**

- Created a nav element and placed the navigation bar on the top.
- Created the main element to contain the logos and form. 
- Used flexbox to align all the logo to the center. 
- Inserted the form element with the input group and labels. 
- Created button element with font awesome logo inside it. 
- Inserted a footer element for the form.
- Created a footer element to finish the project.

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello @ajkacca457 and @Abhigyan001  ! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] **Your linter config files are missing! please add them and fix all your linting errors!**

- [x] Pull Request should have a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))


## Optional 

- [x] add a `for` attribute to your `<label>` tags

- [x] add a `required` attribute to the required inputs (email and password in this case)

- [x] your README is descriptive but with a bad layout! please make look better

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by ajkacca457** [comment]
> # Changes Requested
> Hello @NtwaliHeritier and @Nkuria ! 👋
> Awesome job so far!! 👍 you still need to make some changes though!
> 
> ## Required Changes ♻️
> * [x]  **Your linter config files are missing! please add them and fix all your linting errors!**
> * [x]  Pull Request should have a meaningful title and a brief description (screenshot from Pathwright)
> 
> ## Optional
> * [x]  add a `for` attribute to your `<label>` tags
> * [x]  add a `required` attribute to the required inputs (email and password in this case)
> * [x]  your README is descriptive but with a bad layout! please make look better
> 
> ### please make the appropriate changes and ask for another code review ✔️
> Happy Coding!
> 
> Best,
> Aziz Mejri
> _contact me on [twitter](https://twitter.com/iSpaYco) or slack (@Spayco) if you need any help_

Hello!!
Thank you very much for your in-depth review. We will work tomorrow and will request you again to recheck. I think you mistakenly mentioned someone else name and git account in your review. We are not  @NtwaliHeritier and @Nkuria . We are   @ajkacca457  and @Abhigyan001. Thank you.

**Comment by SpaYco** [comment]
@ajkacca457 yes, sorry about that, i've already fixed it 😉

**Comment by ajkacca457** [comment]
> @ajkacca457 yes, sorry about that, i've already fixed it 😉

Thank you so much. I really appreciate you reviewing our project. Hopefully, with some work we will get your acceptance tomorrow.

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

### Hi @Abhigyan001 and @ajkacca457, you guys did a very good job so far!
#### I can see that you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

- [x] Your Pull Request should have a meaningful title and a brief description ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

Tip: You guys have to describe what you're trying to merge. You can add the features that you both have built in this project, for example. 
 
**Please make the required changes and resubmit for a new code review once you are ready**

As always, I wish you all the very best and see you both at the top🚀

  

<hr>

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

  
<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

## Hello @Abhigyan001 and @ajkacca457 :wave: 

## Thank you for making the requested changes from the last TSE. Congratulations, you may merge and move to the next project, good luck :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
